package me.huigesi.eyesopen.app.column;

import android.database.sqlite.SQLiteDatabase;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

import me.huigesi.eyesopen.mvp.model.entity.Column;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

public class DaoSession extends AbstractDaoSession {

    private final DaoConfig newsChannelTableDaoConfig;

    private final NewsChannelTableDao newsChannelTableDao;

    public DaoSession(Database db,IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);
        newsChannelTableDaoConfig = daoConfigMap.get(NewsChannelTableDao.class).clone();
        newsChannelTableDaoConfig.initIdentityScope(type);

        newsChannelTableDao = new NewsChannelTableDao(newsChannelTableDaoConfig, this);

        registerDao(Column.class, newsChannelTableDao);
    }
    
    public void clear() {
        newsChannelTableDaoConfig.getIdentityScope().clear();
    }

    public NewsChannelTableDao getNewsChannelTableDao() {
        return newsChannelTableDao;
    }

}
