package me.huigesi.eyesopen.app.column;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

import me.huigesi.eyesopen.mvp.model.entity.Column;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "NEWS_CHANNEL_TABLE".
*/
public class NewsChannelTableDao extends AbstractDao<Column, String> {

    public static final String TABLENAME = "NEWS_CHANNEL_TABLE";

    /**
     * Properties of entity NewsChannelTable.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property NewsChannelName = new Property(0, String.class, "newsChannelName", true, "NEWS_CHANNEL_NAME");
        public final static Property NewsChannelId = new Property(1, String.class, "newsChannelId", false, "NEWS_CHANNEL_ID");
        public final static Property NewsChannelType = new Property(2, String.class, "newsChannelType", false, "NEWS_CHANNEL_TYPE");
        public final static Property NewsChannelSelect = new Property(3, boolean.class, "newsChannelSelect", false, "NEWS_CHANNEL_SELECT");
        public final static Property NewsChannelIndex = new Property(4, int.class, "newsChannelIndex", false, "NEWS_CHANNEL_INDEX");
        public final static Property NewsChannelFixed = new Property(5, Boolean.class, "newsChannelFixed", false, "NEWS_CHANNEL_FIXED");
    };


    public NewsChannelTableDao(DaoConfig config) {
        super(config);
    }
    
    public NewsChannelTableDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"NEWS_CHANNEL_TABLE\" (" + //
                "\"NEWS_CHANNEL_NAME\" TEXT PRIMARY KEY NOT NULL ," + // 0: newsChannelName
                "\"NEWS_CHANNEL_ID\" TEXT NOT NULL ," + // 1: newsChannelId
                "\"NEWS_CHANNEL_TYPE\" TEXT NOT NULL ," + // 2: newsChannelType
                "\"NEWS_CHANNEL_SELECT\" INTEGER NOT NULL ," + // 3: newsChannelSelect
                "\"NEWS_CHANNEL_INDEX\" INTEGER NOT NULL ," + // 4: newsChannelIndex
                "\"NEWS_CHANNEL_FIXED\" INTEGER);"); // 5: newsChannelFixed
        // Add Indexes
        db.execSQL("CREATE INDEX " + constraint + "IDX_NEWS_CHANNEL_TABLE_NEWS_CHANNEL_NAME ON NEWS_CHANNEL_TABLE" +
                " (\"NEWS_CHANNEL_NAME\");");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"NEWS_CHANNEL_TABLE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Column readEntity(Cursor cursor, int offset) {
        Column entity = new Column( //
            cursor.getString(offset + 0), // name
            cursor.getString(offset + 1), // id
            cursor.getString(offset + 2), // group
            cursor.getShort(offset + 3) != 0, // select
            cursor.getInt(offset + 4), // index
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0 // fixed
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Column entity, int offset) {
        entity.setName(cursor.getString(offset + 0));
        entity.setId(cursor.getString(offset + 1));
        entity.setGroup(cursor.getString(offset + 2));
        entity.setNewsColumnSelect(cursor.getShort(offset + 3) != 0);
        entity.setNewsColumnIndex(cursor.getInt(offset + 4));
        entity.setNewsColumnFixed(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
     }

    @Override
    protected void bindValues(DatabaseStatement stmt, Column entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getName());
        stmt.bindString(2, entity.getId());
        stmt.bindString(3, entity.getGroup());
        stmt.bindLong(4, entity.isNewsColumnSelect() ? 1L: 0L);
        stmt.bindLong(5, entity.getNewsColumnIndex());

        Boolean newsChannelFixed = entity.getNewsColumnFixed();
        if (newsChannelFixed != null) {
            stmt.bindLong(6, newsChannelFixed ? 1L: 0L);
        }
    }

    @Override
    protected void bindValues(SQLiteStatement stmt, Column entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getName());
        stmt.bindString(2, entity.getId());
        stmt.bindString(3, entity.getGroup());
        stmt.bindLong(4, entity.isNewsColumnSelect() ? 1L: 0L);
        stmt.bindLong(5, entity.getNewsColumnIndex());

        Boolean newsChannelFixed = entity.getNewsColumnFixed();
        if (newsChannelFixed != null) {
            stmt.bindLong(6, newsChannelFixed ? 1L: 0L);
        }
    }

    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Column entity, long rowId) {
        return entity.getName();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Column entity) {
        if(entity != null) {
            return entity.getName();
        } else {
            return null;
        }
    }

    @Override
    protected boolean hasKey(Column entity) {
        return false;
    }

    /** @inheritdoc */
    @Override
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
